### ISSUE TITLE
Script no running on Win10 64bit

### ISSUE THREAD

**Issue by ghost** [bakapear/mixdlr#1]
I first set 
`set-executionpolicy remotesigned`

but mixdlr https://www.mixcloud.com/Radio80K/sepalot-studio-session/ sepalot-studio-session.mp4
lead me to the following error:
`Couldn't parse JSON from Site!`
Is the script still up to date and this just my machine or did mixcloud change their site?

**Comment by bakapear** [comment]
This module is deprecated and does not work anymore
